config/routes.rb
Blog::Application.routes.draw do
  
  devise_for :users
  
  root :to => 'posts#index'
  
  resources :users, :only => [:show, :index]
  resources :posts
  resources :comments, :only => [:new, :create, :destroy]
  resources :tags, :only => [:show, :index]
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :post_id
  
  belongs_to :user
  belongs_to :post
  
  default_scope :order => 'comments.created_at DESC'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
  
  belongs_to :user
  has_many :comments
  has_many :tags, :through => :tagrelations, :source => :tag
  has_many :tagrelations, :dependent => :destroy

  default_scope :order => 'posts.created_at DESC'
  
  def add_tag(tagname)
    tag = Tag.find_or_create_by_name(tagname)
    if tag != nil
      rel = Tagrelation.find_by_post_id_and_tag_id(self.id, tag[:id])
      if rel.nil?
        self.tagrelations.create(:tag_id => tag[:id])
      end
    end
  end
  
  def add_tags(tagnames)
    tagnames.split(' ').each do |tag|
      if not tag.blank? then add_tag(tag) end
    end
  end
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :tag_id, :name
  
  has_many :posts, :through => :tagrelations, :source => :post
  has_many :tagrelations, :dependent => :destroy
end

app/models/tagrelation.rb
class Tagrelation < ActiveRecord::Base
  attr_accessible :tag_id, :post_id
  
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts
  has_many :comments
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :create]
  
  def new
    @user = current_user
    if @user.nil? then
      @comment = Comment.new
    else
      @comment = @user.comments.new
    end
  end
  
  def create
    @post = Post.find_by_id(params["post"]["id"])
    if @post.nil?
      flash[:error] = "Не удалось создать комментарий."
      redirect_to root_path
      return
    end
    @content = params["comment"]["content"]
    @user = current_user
    if @user.nil?
      @comment = Comment.new(:post_id => @post[:id], :content => @content)
    else
      @comment = @user.comments.new(:post_id => @post[:id], :content => @content)
    end
    if not @comment.save
      flash[:error] = "Не удалось создать комментарий."
    end
    redirect_to post_path(@post) + "#comments"
  end
  
end

app/controllers/pages_controller.rb
#coding: utf-8

class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
  
  def help
  end

end

app/controllers/posts_controller.rb
#coding: utf-8

class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def index
    @posts = Post.paginate(:page => params[:page])
  end
  
  def new
    @user = current_user
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(params[:post])
    @tags = params[:post][:tags] 
    if @post.save
      @post.add_tags(@tags)
      flash[:success] = "Запись создана!"
      redirect_to root_path
    else
      flash[:error] = "Не удалось создать запись!"
    end
  end
  
  def destroy
  end
  
  def show
    @post = Post.find(params[:id])
    if current_user.nil?
      @new_comment = @post.comments.new
    else
      @new_comment = current_user.comments.new(:post_id => @post[:id])
    end
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def show
    @tag = Tag.find_by_id(params[:id])
    @posts = @tag.posts.paginate(:page => params[:page])
  end
  
  def index
    @tags = Tag.paginate(:page => params[:page])
  end
end

app/controllers/users_controller.rb
#coding: utf-8

class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(:page => params[:page])
  end
  
  def index
    @users = User.paginate(:page => params[:page])
  end

end

app/helpers/application_helper.rb
#coding: utf-8

module ApplicationHelper
 
  def title
    base_title = "Блог"
    page_title = content_for(:title) 
    if page_title.nil?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
  #Devise
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def post_content_cut(content, length=500)
    truncate_html sanitize(content), :length=>length
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    if not user.nil?
      gravatar_image_tag(user.email.downcase, :alt => user.name,
        :class => 'gravatar',
        :gravatar => options)
    end
  end
end

app/views/comments/_comment.html.erb
<% if comment.created_at != nil  %>
  <div class="comment">
    <div class="comment_bar">
      <%= render 'comments/comment_bar', :comment => comment %>
    </div>
    <div class="content">
      <%= raw sanitize(comment.content) %>
    </div>
  </div>
<% end %>

app/views/comments/_comment_bar.erb
<span class="gravatar">
  <%= gravatar_for comment.user, :size=>"15px" %>
</span>
<span class="author">
  <%= if comment.user.nil? then "Anonymouse" else
    link_to comment.user.name, comment.user end %>
</span>
<span class="timestamp">
  <%= time_ago_in_words(comment.created_at) %> назад
</span>

app/views/layouts/_flash_message.html.erb
<%  flash.each do |key, value| %>
  <%= content_tag(:div, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "О блоге", about_path %></li>
      <li><%= link_to "Теги", tags_path %></li>
      <li><%= link_to "Пользователи", users_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to image_tag("logo.png", :alt => "Логотип", :class => "round"), root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Главная", root_path %></li>
      <% if signed_in?(:user) %>
        <li><%= link_to "Добавить запись", new_post_path %> </li>
        <li><%= link_to "Профиль", current_user %></li>
        <li><%= link_to "Настройки", edit_user_registration_path %></li>
        <li><%= link_to "Выход", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Вход", new_user_session_path %></li>
        <li><%= link_to "Регистрация", new_user_registration_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tags %> 
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= render 'layouts/flash_message' %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<%= content_for :title, "О блоге" %>
<h1>О блоге</h1>
<p>Данный раздел находится в разработке</p>

app/views/pages/contact.html.erb
<%= content_for :title, "Контакты" %>
<h1>К</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<%= content_for :title, "Помощь" %>
<h1>Помощь</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<%= content_for :title, "Главная" %>
<h1>Блог</h1>
<p>
  #начальная страница
</p>

app/views/posts/_post.html.erb
<div class="post round">
  <span class="title">
    <%= link_to post.title, post %>
  </span><br/>
  <span class="content">
    <%= raw post_content_cut(post.content) %><br/>
    <%= link_to "читать", post %>
  </span>
</div>
<%= render 'posts/post_bar', :post => post %>

app/views/posts/_post_bar.html.erb
<div class="post_bar round">
  <span class="gravatar">
    <%= link_to gravatar_for(post.user, :size=>13), post.user %>
  </span>
  <span class="author">
    <%= link_to post.user.name, post.user %>
  </span>
  <span class="timestamp">
    <%= time_tag post.created_at %>
  </span>
  <span class="comments">
    <%= link_to "комментарии(#{post.comments.count})", url_for(post) +"#comments" %>
  </span>
</div>
<br style="clear: both">

app/views/posts/index.html.erb
<%= content_for :title, "Все записи" %>
<h1>Все записи</h1>

<% if @posts.any? %>
  <%= will_paginate %>
  <div class="posts">
    <%= render @posts %>
  </div>
  <%= will_paginate %>
<% else %>
  <span class="empty_message">Список записей пуст</span>
<% end %>

app/views/posts/new.html.erb
<%= content_for :title, "Добавление записи" %>
<h1>Добавление записи</h1>
<%= form_for @post do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title, "Заголовок" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content, "Текст" %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :tags, "Теги" %><br />
    <%= f.text_field :tags, :value => "" %>
  </div>
  <div class="actions">
    <%= f.submit "Послать" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= content_for :title, @post.title %>
<h1><%= @post.title %></h1>
<div class="post_content round">
  <%= raw sanitize(@post.content) %>
</div>

<%= render 'post_bar', :post => @post %>

<div id="post_tag_list">
  <% if @post.tags.any? %>
    Теги:
    <% @post.tags.each do |tag| %>
      <%= link_to tag.name, tag %>
    <% end %>
  <% end %>
</div>

<div id = "comments">
  <%= render "shared/comment_form" %>
  <%= render @post.comments %>
</div>

app/views/shared/_comment_form.html.erb
<%= form_for @new_comment do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :content, "Комментарий" %><br />
    <%= f.text_area :content %>
  </div>
  <%= fields_for @post do |pf| %>
    <%= pf.hidden_field :id, :value => @post.id %>
  <% end %>
  <div class="actions">
    <%= f.submit "Отправить" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<li class="tag">
  <%= link_to tag.name, tag %>
</li>

app/views/tags/index.html.erb
<%= content_for :title, "Все теги" %>
<h1>Все теги</h1>

<%= will_paginate %>

<% if @tags.any? %>
<ul class="tags">
  <%= render @tags %>
</ul>
<% else %>
<span class="empty_message">Список тегов пуст</span>
<% end %>

<%= will_paginate %>

app/views/tags/show.html.erb
<%= content_for :title, "Тег: #{@tag.name}" %>
<h1>Список записей с тегом <b><%= @tag.name %></b></h1>

<%= will_paginate @posts %>

<div class="tag_posts">
  <%= render @posts %>
</div>

<%= will_paginate @posts %>

app/views/users/_user.html.erb
<li class="user">
  <%= gravatar_for user, :size => 16 %>
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<%= content_for :title, "Все пользователи" %>
<h1>Все пользователи</h1>
<%= will_paginate %>

<% if @users.any? %>
  <ul class="users">
    <%= render @users %>
  </ul>
<% else %>
  <span class="empty_message">Список пользователей пуст</span>
<% end %>

<%= will_paginate %>

app/views/users/show.html.erb
<%= content_for :title, "Профиль пользователя" %>
<h1>Профиль пользователя</h1>

<div class="sidebar round">
  <span class="gravatar"><%= gravatar_for @user %></span><br />
  <span class="user_name">Имя: <%= @user.name %></span><br />
  <span class="post_count">Постов: <%= @user.posts.count %></span><br />
  <span class="comments_count">Комментариев: <%= @user.comments.count %></span>
</div>

<% if @posts.any? %> 
  <h2>Записи пользователя</h2>

  <%= will_paginate @posts %>

  <div class="user_posts">
    <%= render @posts %>
  </div>

  <%= will_paginate @posts %>
<% end %>